### ISSUE TITLE
can it be used for categorical data?

### ISSUE THREAD

**Issue by Sandy4321** [matrix-profile-foundation/mass-ts#7]
can it be used for categorical data?
* MASS version:
* Python version:
* Operating System:

### Description

Describe what you were trying to get done.
Tell us what happened, what went wrong, and what you expected to happen.

### What I Did

```
Paste the command(s) you ran and the output.
If there was a crash, please include the traceback here.
```

**Comment by tylerwmarrs** [comment]
I do not think it makes sense to use this for categorical data. Are you able to explain your application in more detail? I may be able to point you in the right direction.

**Comment by Sandy4321** [comment]
I do have one hot encoding data
generated from original data which is mix of categorical and continues data
So  I used buckets for continues data  , to get everything represented as one hot

but for even one hot  I do have multidimensional data
so all vectors for each dimension have different length
