### ISSUE TITLE
Memory issue with MASS3 

### ISSUE THREAD

**Issue by watsondavetrendalyze** [matrix-profile-foundation/mass-ts#8]
* MASS version: 3
Name: mass-ts
Version: 0.1.3
Summary: MASS (Mueen's Algorithm for Similarity Search)
Home-page: https://github.com/tylerwmarrs/mass_ts
Author: Tyler Marrs
Author-email: tylerwmarrs@gmail.com
License: Apache Software License 2.0
Location: /home/rsa-key-20180725/.local/lib/python3.6/site-packages
Requires: numpy

* Python version: 3.6
Python 3.6.8

* Operating System: Ubuntu
Description:    Ubuntu 18.04.1 LTS
Release:        18.04
Codename:       bionic

Time series data length is 460,001
Motif length is 250
Works fine with following call:
distances = mts.mass3(Hsrs, Nsrs, 1024)

Time series data length is 460,001
Motif length is 2,750
distances = mts.mass3(Hsrs, Nsrs, 4096)
Throws exception

---------------------------------------------------------------------------
MemoryError                               Traceback (most recent call last)
<ipython-input-3-33c597b7c5d6> in <module>
     63 print('Motif length is {:,}'.format(len(Nsrs)))
     64 #distances = mts.mass3(Hsrs, Nsrs, 8192)
---> 65 distances = mts.mass3(Hsrs, Nsrs, 4096)
     66 plt.title('PLBB Distances')
     67 plt.plot(distances)

~/.local/lib/python3.6/site-packages/mass_ts/_mass_ts.py in mass3(ts, query, pieces)
    178     meanx = mtscore.moving_average(x, m)
    179     meanx = np.append(np.ones([1, len(x) - len(meanx)]), meanx)
--> 180     sigmax = mtscore.moving_std(x, m)
    181     sigmax = np.append(np.zeros([1, len(x) - len(sigmax)]), sigmax)
    182 

~/.local/lib/python3.6/site-packages/mass_ts/core.py in moving_std(a, window)
    140     The moving std. over the array.
    141     """
--> 142     return np.std(rolling_window(a, window), -1)
    143 
    144 

<__array_function__ internals> in std(*args, **kwargs)

~/.local/lib/python3.6/site-packages/numpy/core/fromnumeric.py in std(a, axis, dtype, out, ddof, keepdims)
   3379 
   3380     return _methods._std(a, axis=axis, dtype=dtype, out=out, ddof=ddof,
-> 3381                          **kwargs)
   3382 
   3383 

~/.local/lib/python3.6/site-packages/numpy/core/_methods.py in _std(a, axis, dtype, out, ddof, keepdims)
    215 def _std(a, axis=None, dtype=None, out=None, ddof=0, keepdims=False):
    216     ret = _var(a, axis=axis, dtype=dtype, out=out, ddof=ddof,
--> 217                keepdims=keepdims)
    218 
    219     if isinstance(ret, mu.ndarray):

~/.local/lib/python3.6/site-packages/numpy/core/_methods.py in _var(a, axis, dtype, out, ddof, keepdims)
    191     # Note that x may not be inexact and that we need it to be an array,
    192     # not a scalar.
--> 193     x = asanyarray(arr - arrmean)
    194     if issubclass(arr.dtype.type, (nt.floating, nt.integer)):
    195         x = um.multiply(x, x, out=x)

MemoryError: Unable to allocate array with shape (457252, 2750) and data type float64

**Comment by watsondavetrendalyze** [comment]
Same data on MASS2 has no memory issues

![image](https://user-images.githubusercontent.com/15146123/64960137-947fca00-d88a-11e9-82e0-3e9e0052b427.png)

![image](https://user-images.githubusercontent.com/15146123/64960172-acefe480-d88a-11e9-8226-f79ff1299c18.png)

**Comment by tylerwmarrs** [comment]
What implementation of MASS2 are you using? More specifically, your code reflects a parallel version of it. Is this MASS2_batch?

**Comment by watsondavetrendalyze** [comment]
MASS2 Batch

top_matches = 10
batch_size = 10000
n_jobs = 8
best_indices, best_dists = mts.mass2_batch(Hsrs, Nsrs, batch_size=batch_size, top_matches=top_matches, n_jobs=n_jobs)

**Comment by tylerwmarrs** [comment]
MASS3 is not optimized for memory usage. MASS2_batch only finds similar sub sequences while MASS3 stores the entire distance profile in memory and returns that. That is why you are seeing the error that you do.
